language: objective-c
xcode_project: LGTravis/LGTravis.xcodeproj
xcode_scheme: LGTravis
osx_image: xcode11

script:
- xcodebuild test -project "LGTravis/LGTravis.xcodeproj" -scheme "LGTravis" -destination "name=iPhone 11" -enableCodeCoverage YES

after_success:
- bash <(curl -s https://codecov.io/bash)
