language: objective-c
xcode_project: LGTravis/LGTravis.xcodeproj
xcode_scheme: LGTravis
osx_image: xcode11

script:
- xcodebuild -project "LGTravis/LGTravis.xcodeproj" -scheme "LGTravis" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

after_success:
- bash <(curl -s https://codecov.io/bash)
